-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 01:23:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Courses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Courses` DEFAULT CHARACTER SET utf8 ;
USE `Courses` ;

-- -----------------------------------------------------
-- Table `Courses`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses`.`Teacher` (
  `id` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Surname` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Courses`.`LocalCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses`.`LocalCourses` (
  `id` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Program` VARCHAR(512) NOT NULL,
  `Teacher` INT NOT NULL,
  `lab` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Teacher1_idx` (`Teacher` ASC) VISIBLE,
  CONSTRAINT `Teacher1`
    FOREIGN KEY (`Teacher`)
    REFERENCES `Courses`.`Teacher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Courses`.`OffsiteCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses`.`OffsiteCourses` (
  `id` INT NOT NULL,
  `Name` VARCHAR(128) NOT NULL,
  `Program` VARCHAR(512) NOT NULL,
  `Teacher` INT NOT NULL,
  `City` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Teacher2_idx` (`Teacher` ASC) VISIBLE,
  CONSTRAINT `Teacher2`
    FOREIGN KEY (`Teacher`)
    REFERENCES `Courses`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
